// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk2IGdNCUrEPVxh1QXOplTYy-9i7LAPZY',
    appId: '1:693305952436:android:95a3898d7ea93f72a36fe1',
    messagingSenderId: '693305952436',
    projectId: 'flutter-apps-using-firebase',
    storageBucket: 'flutter-apps-using-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd4rOpJTgZmMZzh-bvQV0DxQTu0gHY8kk',
    appId: '1:693305952436:ios:c537557c26c5090ba36fe1',
    messagingSenderId: '693305952436',
    projectId: 'flutter-apps-using-firebase',
    storageBucket: 'flutter-apps-using-firebase.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLiveScoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtwHdSXwggzZD8XnVUndgeL2YUXd6TCDY',
    appId: '1:693305952436:web:94aa708e98fe883fa36fe1',
    messagingSenderId: '693305952436',
    projectId: 'flutter-apps-using-firebase',
    authDomain: 'flutter-apps-using-firebase.firebaseapp.com',
    storageBucket: 'flutter-apps-using-firebase.firebasestorage.app',
    measurementId: 'G-E1721NMXG2',
  );
}
